notifications:
  email: false
language: generic
matrix:
  include:
  - os: linux
    env: BUNDLE_EXT=tar.gz
  - os: osx
    env: BUNDLE_EXT=tar.gz
  - os: windows
    language: shell
    env: BUNDLE_EXT=zip
    install:
    - choco install make
cache:
  directories:
  - _build/chez
script:
- make fetch-kernel
- make fetch-prebuilt
- make precompile
- make
- make test
before_deploy:
- make binary-release
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    make source-release;
  fi;
deploy:
  provider: releases
  api_key:
    secure: gzHYs38Vooes7He/JoyvPBms9DAJPn+rIkrotqqa6BtZCT3P40m5HsNR/bA5mpaJE7mIqht805Tpo1wbocdyAH+zl6qtjdhfnmIVOm4zROMoNS9j++1T8C878vlET4NCfBmaipCSfU6o8yKq05qEDrGWpUnlenDP86a4tgBkBF9tzuxpmmkgKjFz8YaM7/bl6THROLVa1/HyD6zaPCsi8hEIX60EF1Lf+h5MWilY7ScC9+L4WRKJ+BKgiiP+jUE1x6mHeGeSY0WarJvK6FUY60auOJot387jot9Q0Sk4o7Q8IGjumTGveZvtwqfd9QHi4GHDY8MBBubEwBWeAD7Rht6Gm29yISvlpLNSgbK0LEuFyvugXl5DLwnjIdItzIPcNBw5KddCZiALhmyzpRrKkEtAyAW0O3OAfcU1l/q3+3C4vPCuUZkTerAzEU12SP6pF0aJ+0WSgcjwR2IKujftXNgyKjCmEUjfxLzYitil4GGhGLRdQgJnoFIChOIRhYJlu5+EDy4S/eMCAVOF4LhYb1tP9rgMtYc64iR/fxPcJNUGAH+K6IzgG/dur8KUUchncW5iYiJaw4xcdMhgWbEn49N3k1KYLlawPZSwRIy2GzN+6b7WSDASkaRPGGuFbQDzBbINCx9p7XWbPXf2rtIsHmCBrhDEqvzjvpe6Mw+fEXg=
  file:
  - _dist/shen-scheme-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-bin.${BUNDLE_EXT}
  - _dist/shen-scheme-${TRAVIS_TAG}-src.tar.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: tizoc/shen-scheme
