notifications:
  email: false
language: generic
matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
      language: shell
install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install make;
    fi;
script:
  - make fetch-kernel
  - make fetch-shencl
  - make precompile
  - make
  - make test
